#
#server:
#  port: 8081
#spring.cloud.stream:
#  function:
#    definition : pageEventConsumer;pageEventSupplier;pageStreamConsumer;kStreamFunction
#  bindings:
#    pageEventConsumer-in-0:
#      destination: R1
#      group: G1
#    pageEventSupplier-out-0:
#      destination: R3
#    kStreamFunction-in-0:
#      destination: R2
#      group: G44
#    kStreamFunction-out-0:
#      destination: R4
#spring:
#  kafka:
#    streams:
#      application-id: app2
#    consumer:
#      enable-auto-commit: true
#      auto-offset-reset: earliest